### ISSUE TITLE
Description field missing from LetterEditable class

### ISSUE THREAD

**Issue by eeldar-attune** [lob/lob-typescript-sdk#146]
## Summary

The LetterEditable class does not have a description field, as is available in all other Lob SDKs.

## Expected Behavior

I should be able to add a description field as part of my letter which will populate the description field on Lob

## Current Behavior

There is no description field available.

## Possible Solution

Add the description field in, and add it to the SDKs internal API call.

## Steps to Reproduce

N/A

## Context (Environment)

My company requires me to add descriptions to the letters in order for our OPs team to be able to differentiate them in the portal.

**Comment by ShariqT** [comment]
We'll get on this. I'll let you know when we have new release that has this fix.

**Comment by ShariqT** [comment]
Also, as an FYI, you can search for metadata attached to your Letters in the searchbox on the Dashboard. If you want even finer results than what the description field can hold.

**Comment by ShariqT** [comment]
Ok, so your issue with the description has been fixed up. Take look at the newest version of the SDK https://www.npmjs.com/package/@lob/lob-typescript-sdk.

**Comment by eeldar-attune** [comment]
Awesome! I really appreciate your quick response on this.

**Comment by eeldar-attune** [comment]
I'm getting some errors trying to install the latest version 0.0.6 . Both Yarn and NPM are saying that the package file doesn't exist in their registry, despite it appearing on the npmjs website. Here is the specific NPM error I get: 
```
29103 error 404 Not Found - GET https://registry.npmjs.org/@lob/lob-typescript-sdk/-/lob-typescript-sdk-0.0.6.tgz
29104 error 404
29105 error 404 '@lob/lob-typescript-sdk@^0.0.6' is not in the npm registry.
```
Have you been able to download it from NPM on your own machines?

**Comment by eeldar-attune** [comment]
Great, works on my end, thanks for your help! Feel free to close this issue

**Comment by ShariqT** [comment]
Glad we could fix this up for you!
