### ISSUE TITLE
Properties missing on the Letter class

### ISSUE THREAD

**Issue by dpaladin** [lob/lob-typescript-sdk#235]
## Summary

There are properties missing in the create letter response (Letter class), in this case i need **url**

## Expected Behavior

All properties specified in https://docs.lob.com/#tag/Letters/operation/letter_create should be included

## Current Behavior

There is no url in the response object.

## Possible Solution

Add the missing field(s)

## Context (Environment)

Using version 1.0, **url** is one of the few properties i need, the old sdk did work properly

**Comment by BennyKitchell** [comment]
Hey @dpaladin 

Thanks for bringing this to our attention, I am going to take a look into this and let you know a time frame in the next few days.

**Comment by BennyKitchell** [comment]
@dpaladin I have added the url into the Letter response, it will be out in the next release which will be by end of the week.

**Comment by BennyKitchell** [comment]
@dpaladin  The new version of the typescript sdk can be found via npm or directly [here](https://www.npmjs.com/package/@lob/lob-typescript-sdk). It now includes the url in the Letter response. I will leave this issue open for a few days to give you a chance to verify. Thanks!
